// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let values_raw = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25
  ];
  let values = values_raw.map(item => JsxRuntime.jsx(Button.make, {
    children: item.toString(),
    className: "m-1"
  }));
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: values,
        className: "grid content-start gap-1 grid-cols-5"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx(Button.make, {
          children: `Solve`,
          onClick: param => {
            console.log("Solve button clicked");
          }
        }),
        className: "my-4"
      })
    ],
    className: "max-w-1200"
  });
}

let make = App;

export {
  make,
}
/* Button Not a pure module */
