// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cell from "./Cell.res.mjs";
import * as React from "react";
import * as Button from "./Button.res.mjs";
import * as Solver from "./Solver.res.mjs";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let values_initial = [
    0,
    0,
    0,
    0,
    0,
    0,
    8,
    0,
    9,
    0,
    0,
    5,
    0,
    0,
    7,
    0,
    2,
    3,
    0,
    0,
    0,
    0,
    5,
    0,
    1,
    6,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    7,
    0,
    0,
    5,
    2,
    0,
    3,
    0,
    0,
    0,
    8,
    1,
    0,
    0,
    7,
    0,
    9,
    0,
    0,
    0,
    0,
    9,
    0,
    0,
    1,
    0,
    3,
    0,
    0,
    8,
    0,
    3,
    0,
    0,
    0,
    8,
    0,
    0,
    0,
    0,
    0,
    6,
    0,
    0,
    0,
    0,
    0,
    0
  ];
  let match = React.useState(() => values_initial);
  let set_values_raw = match[1];
  let values_raw = match[0];
  let match$1 = React.useState(() => []);
  let set_values_disp = match$1[1];
  React.useEffect(() => {
    set_values_disp(param => values_raw.map((item, idx) => {
      let cellstyle;
      switch (item) {
        case -1 :
          cellstyle = "error";
          break;
        case 0 :
          cellstyle = "unknown";
          break;
        default:
          cellstyle = "default";
      }
      return JsxRuntime.jsx(Cell.make, {
        cellstyle: cellstyle,
        value: item.toString(),
        onChange: event => {
          let newVal = event.currentTarget.value;
          set_values_raw(oldValues => {
            let newValues = oldValues.slice(0);
            newValues[idx] = Belt_Option.getWithDefault(Stdlib_Int.fromString(newVal, undefined), 0);
            return newValues;
          });
        },
        idx: idx
      }, idx.toString());
    }));
  }, [values_raw]);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: match$1[0],
        className: "grid content-start gap-1 grid-cols-9"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx(Button.make, {
          children: `Solve`,
          onClick: param => {
            let solution = Solver.solve(values_raw);
            console.log("solution: " + solution.map(val => val.toString()).join(", "));
            set_values_raw(_oldValues => solution.slice(0));
          }
        }),
        className: "my-4"
      })
    ],
    className: "max-w-1200"
  });
}

let make = App;

export {
  make,
}
/* Cell Not a pure module */
