// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Cell(props) {
  let idx = props.idx;
  let style_class;
  switch (props.cellstyle) {
    case "default" :
      style_class = "bg-blue-500 text-white";
      break;
    case "error" :
      style_class = "bg-red-500 text-white";
      break;
    case "unknown" :
      style_class = "bg-gray-500 text-white";
      break;
    default:
      style_class = "bg-orange-500 text-white";
  }
  let style_class$1 = style_class + " text-center w-7 border border-gray-700 rounded";
  let match = idx % 9;
  let match$1 = idx / 9 | 0;
  let pos_class;
  let exit = 0;
  switch (match) {
    case 2 :
    case 5 :
    case 8 :
      pos_class = match$1 > 5 || match$1 < 2 ? (
          match$1 !== 8 ? "border-r-4" : "border-r-4 border-b-4"
        ) : (
          match$1 !== 4 && match$1 !== 3 ? "border-r-4 border-b-4" : "border-r-4"
        );
      break;
    default:
      exit = 1;
  }
  if (exit === 1) {
    pos_class = match$1 > 5 || match$1 < 2 ? (
        match$1 !== 8 ? "" : "border-b-4"
      ) : (
        match$1 !== 4 && match$1 !== 3 ? "border-b-4" : ""
      );
  }
  return JsxRuntime.jsx("input", {
    className: style_class$1 + " " + pos_class,
    type: "text",
    value: props.value,
    onChange: props.onChange
  });
}

let make = Cell;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
