// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utilities from "./Utilities.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Strategies from "./Strategies.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let sudoku = [
  0,
  0,
  0,
  0,
  0,
  0,
  8,
  0,
  9,
  0,
  0,
  5,
  0,
  0,
  7,
  0,
  2,
  3,
  0,
  0,
  0,
  0,
  5,
  0,
  1,
  6,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  7,
  0,
  0,
  5,
  2,
  0,
  3,
  0,
  0,
  0,
  8,
  1,
  0,
  0,
  7,
  0,
  9,
  0,
  0,
  0,
  0,
  9,
  0,
  0,
  1,
  0,
  3,
  0,
  0,
  8,
  0,
  3,
  0,
  0,
  0,
  8,
  0,
  0,
  0,
  0,
  0,
  6,
  0,
  0,
  0,
  0,
  0,
  0
];

if (sudoku.length !== 81) {
  throw {
    RE_EXN_ID: "Failure",
    _1: "Invalid sudoku",
    Error: new Error()
  };
}

function easyStrategies(_sudoku) {
  while (true) {
    let sudoku = _sudoku;
    let originalSudoku = Belt_Array.concatMany([sudoku]);
    let sudoku$1 = Strategies.hiddenSingle(Strategies.nakedSingle(sudoku, undefined), undefined);
    if (Primitive_object.equal(originalSudoku, sudoku$1)) {
      return sudoku$1;
    }
    _sudoku = sudoku$1;
    continue;
  };
}

function mediumStrategies(_sudoku) {
  while (true) {
    let sudoku = _sudoku;
    let originalSudoku = Belt_Array.concatMany([sudoku]);
    let sudoku$1 = Strategies.nakedPair(Strategies.intersection(sudoku, undefined), undefined);
    if (Primitive_object.equal(originalSudoku, sudoku$1)) {
      return sudoku$1;
    }
    _sudoku = sudoku$1;
    continue;
  };
}

function hardStrategies(_sudoku) {
  while (true) {
    let sudoku = _sudoku;
    let originalSudoku = Belt_Array.concatMany([sudoku]);
    let sudoku$1 = Strategies.hiddenPair(sudoku, undefined);
    if (Primitive_object.equal(originalSudoku, sudoku$1)) {
      return sudoku$1;
    }
    _sudoku = sudoku$1;
    continue;
  };
}

console.log(Utilities.toRows(hardStrategies(mediumStrategies(easyStrategies(sudoku)))));

export {
  sudoku,
  easyStrategies,
  mediumStrategies,
  hardStrategies,
}
/*  Not a pure module */
