// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Strategies from "./Strategies.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function solve(sudoku) {
  if (sudoku.length !== 81) {
    throw {
      RE_EXN_ID: "Failure",
      _1: "Invalid sudoku",
      Error: new Error()
    };
  }
  let easyStrategies = _sudoku => {
    while (true) {
      let sudoku = _sudoku;
      let originalSudoku = Belt_Array.concatMany([sudoku]);
      let sudoku$1 = Strategies.hiddenSingle(Strategies.nakedSingle(sudoku, undefined), undefined);
      if (Primitive_object.equal(originalSudoku, sudoku$1)) {
        return sudoku$1;
      }
      _sudoku = sudoku$1;
      continue;
    };
  };
  let mediumStrategies = _sudoku => {
    while (true) {
      let sudoku = _sudoku;
      let originalSudoku = Belt_Array.concatMany([sudoku]);
      let sudoku$1 = Strategies.nakedPair(Strategies.intersection(sudoku, undefined), undefined);
      if (Primitive_object.equal(originalSudoku, sudoku$1)) {
        return sudoku$1;
      }
      _sudoku = sudoku$1;
      continue;
    };
  };
  let _sudoku = mediumStrategies(easyStrategies(sudoku));
  while (true) {
    let sudoku$1 = _sudoku;
    let originalSudoku = Belt_Array.concatMany([sudoku$1]);
    let sudoku$2 = Strategies.hiddenPair(sudoku$1, undefined);
    if (Primitive_object.equal(originalSudoku, sudoku$2)) {
      return sudoku$2;
    }
    _sudoku = sudoku$2;
    continue;
  };
}

export {
  solve,
}
/* No side effect */
