// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utilities from "./Utilities.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function nakedSingle(sudoku, candidatesMapOpt) {
  let candidatesMap = candidatesMapOpt !== undefined ? candidatesMapOpt : Utilities.toCandidates(sudoku);
  candidatesMap.entries().toArray().forEach(param => {
    let possibleValues = param[1];
    if (possibleValues.length === 1) {
      sudoku[param[0]] = Stdlib_Option.getExn(possibleValues[0], undefined);
      return;
    }
  });
  return sudoku;
}

function hiddenSingle(sudoku, candidatesMapOpt) {
  let candidatesMap = candidatesMapOpt !== undefined ? candidatesMapOpt : Utilities.toCandidates(sudoku);
  candidatesMap.entries().toArray().forEach(param => {
    let key = param[0];
    let rowIndexes = Utilities.getRowKeysForKey(key);
    let columnIndexes = Utilities.getColumnKeysForKey(key);
    let boxIndexes = Utilities.getBoxKeysForKey(key);
    let rowCandidates = rowIndexes.map(key => Stdlib_Option.getOr(candidatesMap.get(key), []));
    let columnCandidates = columnIndexes.map(key => Stdlib_Option.getOr(candidatesMap.get(key), []));
    let boxCandidates = boxIndexes.map(key => Stdlib_Option.getOr(candidatesMap.get(key), []));
    [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ].forEach(value => {
      if (rowCandidates.flat().filter(v => v === value).length === 1) {
        let index = rowCandidates.findIndex(candidates => candidates.includes(value));
        sudoku[Stdlib_Option.getExn(rowIndexes[index], undefined)] = value;
      }
      if (columnCandidates.flat().filter(v => v === value).length === 1) {
        let index$1 = columnCandidates.findIndex(candidates => candidates.includes(value));
        sudoku[Stdlib_Option.getExn(columnIndexes[index$1], undefined)] = value;
      }
      if (boxCandidates.flat().filter(v => v === value).length !== 1) {
        return;
      }
      let index$2 = boxCandidates.findIndex(candidates => candidates.includes(value));
      sudoku[Stdlib_Option.getExn(boxIndexes[index$2], undefined)] = value;
    });
  });
  return nakedSingle(sudoku, candidatesMap);
}

function intersection(sudoku, candidatesMapOpt) {
  let candidatesMap = candidatesMapOpt !== undefined ? candidatesMapOpt : Utilities.toCandidates(sudoku);
  candidatesMap.entries().toArray().forEach(param => {
    let key = param[0];
    let rowIndexes = Utilities.getRowKeysForKey(key);
    let columnIndexes = Utilities.getColumnKeysForKey(key);
    let boxIndexes = Utilities.getBoxKeysForKey(key);
    let boxCandidates = Utilities.getUnitCandidatesForKeys(boxIndexes, candidatesMap);
    let getCandidatesThatMustExistInBox = () => {
      let candidates = boxCandidates.map(param => param.unitCandidates);
      let indexes = [
        0,
        1,
        2
      ].map(n => n * 3 | 0);
      let boxRowCandidates = indexes.map((start, end) => {
        let end$1 = indexes[end + 1 | 0];
        if (end$1 !== undefined) {
          return candidates.slice(start, end$1).flat();
        } else {
          return candidates.slice(start).flat();
        }
      });
      let indexes$1 = [
        0,
        1,
        2
      ];
      let boxColumnCandidates = indexes$1.map(columnIndex => candidates.filter((param, index) => index % 3 === columnIndex).flat());
      let isCandidateUniqueToRowOrColumn = (currentBoxRowOrColumn, boxCandidates, candidate) => {
        switch (currentBoxRowOrColumn) {
          case 0 :
            if (Stdlib_Option.getExn(boxCandidates[0], undefined).includes(candidate) && !Stdlib_Option.getExn(boxCandidates[1], undefined).includes(candidate)) {
              return !Stdlib_Option.getExn(boxCandidates[2], undefined).includes(candidate);
            } else {
              return false;
            }
          case 1 :
            if (Stdlib_Option.getExn(boxCandidates[1], undefined).includes(candidate) && !Stdlib_Option.getExn(boxCandidates[0], undefined).includes(candidate)) {
              return !Stdlib_Option.getExn(boxCandidates[2], undefined).includes(candidate);
            } else {
              return false;
            }
          case 2 :
            if (Stdlib_Option.getExn(boxCandidates[2], undefined).includes(candidate) && !Stdlib_Option.getExn(boxCandidates[0], undefined).includes(candidate)) {
              return !Stdlib_Option.getExn(boxCandidates[1], undefined).includes(candidate);
            } else {
              return false;
            }
          default:
            throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "Strategies.res",
                114,
                15
              ],
              Error: new Error()
            };
        }
      };
      let currentBoxRow = Utilities.floor(boxIndexes.indexOf(key) / 3 | 0);
      let currentBoxColumn = boxIndexes.indexOf(key) % 3;
      return Stdlib_Array.reduce([
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ], [
        [],
        []
      ], (param, candidate) => {
        let uniqueColumnCandidates = param[1];
        let uniqueRowCandidates = param[0];
        let isUniqueRowCandidate = isCandidateUniqueToRowOrColumn(currentBoxRow, boxRowCandidates, candidate);
        let isUniqueColumnCandidate = isCandidateUniqueToRowOrColumn(currentBoxColumn, boxColumnCandidates, candidate);
        return [
          isUniqueRowCandidate ? Belt_Array.concatMany([
              uniqueRowCandidates,
              [candidate]
            ]) : uniqueRowCandidates,
          isUniqueColumnCandidate ? Belt_Array.concatMany([
              uniqueColumnCandidates,
              [candidate]
            ]) : uniqueColumnCandidates
        ];
      });
    };
    let match = getCandidatesThatMustExistInBox();
    let columnCandidatesToRemoveOutsideOfBox = match[1];
    let rowCandidatesToRemoveOutsideOfBox = match[0];
    rowIndexes.filter(index => !boxIndexes.includes(index)).forEach(index => {
      rowCandidatesToRemoveOutsideOfBox.forEach(candidate => Utilities.removeCandidate(index, candidate, candidatesMap));
    });
    columnIndexes.filter(index => !boxIndexes.includes(index)).forEach(index => {
      columnCandidatesToRemoveOutsideOfBox.forEach(candidate => Utilities.removeCandidate(index, candidate, candidatesMap));
    });
  });
  return hiddenSingle(sudoku, candidatesMap);
}

function nakedPair(sudoku, candidatesMapOpt) {
  let candidatesMap = candidatesMapOpt !== undefined ? candidatesMapOpt : Utilities.toCandidates(sudoku);
  candidatesMap.entries().toArray().forEach(param => {
    let key = param[0];
    let rowIndexes = Utilities.getRowKeysForKey(key);
    let columnIndexes = Utilities.getColumnKeysForKey(key);
    let boxIndexes = Utilities.getBoxKeysForKey(key);
    let getPairs = candidates => candidates.filter((param, index) => {
      let unitCandidates = param.unitCandidates;
      if (unitCandidates.length === 2) {
        return candidates.some((param, i) => {
          if (index !== i) {
            return Primitive_object.equal(unitCandidates, param.unitCandidates);
          } else {
            return false;
          }
        });
      } else {
        return false;
      }
    });
    let removePairCandidatesFromRemainderOfUnit = (unitIndexes, pairs) => {
      pairs.forEach(param => {
        let unitCandidates = param.unitCandidates;
        unitIndexes.forEach(index => {
          let candidatesForIndex = Stdlib_Option.getOr(candidatesMap.get(index), []);
          if (Primitive_object.notequal(candidatesForIndex, unitCandidates) && candidatesForIndex.length !== 0) {
            unitCandidates.forEach(candidate => Utilities.removeCandidate(index, candidate, candidatesMap));
            return;
          }
        });
      });
    };
    let rowCandidates = Utilities.getUnitCandidatesForKeys(rowIndexes, candidatesMap);
    let columnCandidates = Utilities.getUnitCandidatesForKeys(columnIndexes, candidatesMap);
    let boxCandidates = Utilities.getUnitCandidatesForKeys(boxIndexes, candidatesMap);
    let pairsInRow = getPairs(rowCandidates);
    let pairsInColumn = getPairs(columnCandidates);
    let pairsInBox = getPairs(boxCandidates);
    removePairCandidatesFromRemainderOfUnit(rowIndexes, pairsInRow);
    removePairCandidatesFromRemainderOfUnit(columnIndexes, pairsInColumn);
    removePairCandidatesFromRemainderOfUnit(boxIndexes, pairsInBox);
  });
  return intersection(sudoku, candidatesMap);
}

function hiddenPair(sudoku, candidatesMapOpt) {
  let candidatesMap = candidatesMapOpt !== undefined ? candidatesMapOpt : Utilities.toCandidates(sudoku);
  candidatesMap.entries().toArray().forEach(param => {
    let key = param[0];
    let rowIndexes = Utilities.getRowKeysForKey(key);
    let columnIndexes = Utilities.getColumnKeysForKey(key);
    let boxIndexes = Utilities.getBoxKeysForKey(key);
    let getHiddenPairs = candidates => {
      let map = new Map();
      candidates.flatMap(param => param.unitCandidates).forEach(candidate => {
        map.set(candidate, Stdlib_Option.getOr(map.get(candidate), 0) + 1 | 0);
      });
      let candidatesAppearingExactlyTwiceInUnit = map.entries().toArray().filter(param => param[1] === 2).map(param => param[0]);
      let unitCandidatesContainingAtTwoCandidatesThatEachAppearExactlyTwiceInUnit = candidates.filter(param => {
        let candidatesInUnit = param.unitCandidates.filter(candidate => candidatesAppearingExactlyTwiceInUnit.includes(candidate));
        return candidatesInUnit.length === 2;
      });
      if (unitCandidatesContainingAtTwoCandidatesThatEachAppearExactlyTwiceInUnit.length === 2) {
        return [
          unitCandidatesContainingAtTwoCandidatesThatEachAppearExactlyTwiceInUnit,
          candidatesAppearingExactlyTwiceInUnit.filter(candidate => unitCandidatesContainingAtTwoCandidatesThatEachAppearExactlyTwiceInUnit.flatMap(param => param.unitCandidates).includes(candidate))
        ];
      }
    };
    let removeOtherCandidatesFromHiddenPair = (hiddenPairs, candidatesInPair) => {
      hiddenPairs.forEach(param => {
        let key = param.key;
        candidatesMap.set(key, Stdlib_Option.getExn(candidatesMap.get(key), undefined).filter(candidate => candidatesInPair.includes(candidate)));
      });
    };
    let rowCandidates = Utilities.getUnitCandidatesForKeys(rowIndexes, candidatesMap);
    let columnCandidates = Utilities.getUnitCandidatesForKeys(columnIndexes, candidatesMap);
    let boxCandidates = Utilities.getUnitCandidatesForKeys(boxIndexes, candidatesMap);
    let match = getHiddenPairs(rowCandidates);
    if (match !== undefined) {
      removeOtherCandidatesFromHiddenPair(match[0], match[1]);
    }
    let match$1 = getHiddenPairs(columnCandidates);
    if (match$1 !== undefined) {
      removeOtherCandidatesFromHiddenPair(match$1[0], match$1[1]);
    }
    let match$2 = getHiddenPairs(boxCandidates);
    if (match$2 !== undefined) {
      return removeOtherCandidatesFromHiddenPair(match$2[0], match$2[1]);
    }
  });
  return nakedPair(sudoku, candidatesMap);
}

export {
  nakedSingle,
  hiddenSingle,
  intersection,
  nakedPair,
  hiddenPair,
}
/* No side effect */
