// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function floor(n) {
  return Math.floor(n) | 0;
}

function toRows(sudoku) {
  let indexes = [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8
  ].map(n => n * 9 | 0);
  return indexes.map((start, end) => {
    let end$1 = indexes[end + 1 | 0];
    if (end$1 !== undefined) {
      return sudoku.slice(start, end$1);
    } else {
      return sudoku.slice(start);
    }
  });
}

function toColumns(sudoku) {
  let indexes = [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8
  ];
  return indexes.map(columnIndex => sudoku.filter((param, index) => index % 9 === columnIndex));
}

function toBoxes(sudoku) {
  return Stdlib_Array.reduceWithIndex(sudoku, [], (boxes, value, key) => {
    let row = Math.floor(key / 9 | 0) | 0;
    let column = key % 9;
    let boxIndex = ((Math.floor(row / 3 | 0) | 0) * 3 | 0) + (Math.floor(column / 3 | 0) | 0) | 0;
    let box = boxes[boxIndex];
    boxes[boxIndex] = box !== undefined ? (box.push(value), box) : [value];
    return boxes;
  });
}

function toCandidates(sudoku) {
  let candidates = new Map();
  let rows = toRows(sudoku);
  let columns = toColumns(sudoku);
  let boxes = toBoxes(sudoku);
  sudoku.forEach((value, key) => {
    if (value === 0) {
      candidates.set(key, [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ].filter(value => {
        let rowIndex = Math.floor(key / 9 | 0) | 0;
        let columnIndex = key % 9;
        let boxIndex = ((Math.floor(rowIndex / 3 | 0) | 0) * 3 | 0) + (Math.floor(columnIndex / 3 | 0) | 0) | 0;
        let row = Stdlib_Option.getExn(rows[rowIndex], undefined);
        let column = Stdlib_Option.getExn(columns[columnIndex], undefined);
        let box = Stdlib_Option.getExn(boxes[boxIndex], undefined);
        return !(row.includes(value) || column.includes(value) || box.includes(value));
      }));
      return;
    }
  });
  return candidates;
}

function getRowKeysForKey(key) {
  let key$1 = (Math.floor(key / 9 | 0) | 0) * 9 | 0;
  return [
    key$1,
    key$1 + 1 | 0,
    key$1 + 2 | 0,
    key$1 + 3 | 0,
    key$1 + 4 | 0,
    key$1 + 5 | 0,
    key$1 + 6 | 0,
    key$1 + 7 | 0,
    key$1 + 8 | 0
  ];
}

function getColumnKeysForKey(key) {
  let key$1 = key % 9;
  return [
    key$1,
    key$1 + 9 | 0,
    key$1 + 18 | 0,
    key$1 + 27 | 0,
    key$1 + 36 | 0,
    key$1 + 45 | 0,
    key$1 + 54 | 0,
    key$1 + 63 | 0,
    key$1 + 72 | 0
  ];
}

function getBoxKeysForKey(key) {
  let rowIndex = Math.floor(key / 9 | 0) | 0;
  let columnIndex = key % 9;
  let boxIndex = ((Math.floor(rowIndex / 3 | 0) | 0) * 3 | 0) + (Math.floor(columnIndex / 3 | 0) | 0) | 0;
  let key$1 = ((Math.floor(boxIndex / 3 | 0) | 0) * 27 | 0) + (boxIndex % 3 * 3 | 0) | 0;
  return [
    key$1,
    key$1 + 1 | 0,
    key$1 + 2 | 0,
    key$1 + 9 | 0,
    key$1 + 10 | 0,
    key$1 + 11 | 0,
    key$1 + 18 | 0,
    key$1 + 19 | 0,
    key$1 + 20 | 0
  ];
}

function getUnitCandidatesForKeys(keys, candidatesMap) {
  return keys.map(index => Stdlib_Option.getOr(candidatesMap.get(index), [])).map((candidates, index) => ({
    unitCandidates: candidates,
    index: index,
    key: Stdlib_Option.getExn(keys[index], undefined)
  }));
}

function removeCandidate(key, candidate, candidatesMap) {
  let candidates = Stdlib_Option.getOr(candidatesMap.get(key), []);
  if (candidates.length !== 0) {
    candidatesMap.set(key, candidates.filter(c => c !== candidate));
    return;
  }
}

export {
  floor,
  toRows,
  toColumns,
  toBoxes,
  toCandidates,
  getRowKeysForKey,
  getColumnKeysForKey,
  getBoxKeysForKey,
  getUnitCandidatesForKeys,
  removeCandidate,
}
/* No side effect */
